# Generated by Django 6.0.4 on 2026-05-03 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('buyer', 'buyer'), ('seller', 'seller')], default='buyer'),
        ),
    ]
